[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 8080
  publish = "dist"
  framework = "vite"
  functionsPort = 9999

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]
  # Netlify free plan: 10 second max timeout

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Note: On free plan, all functions are limited to 10 seconds max
[functions.openai-proxy]
  included_files = ["netlify/functions/**"]
  memory = 1024

[functions.openai-stream]
  included_files = ["netlify/functions/**"]
  memory = 1024

[functions.azure-translate]
  included_files = ["netlify/functions/**"]
  memory = 256
